/* eslint-disable react-refresh/only-export-components */
import React, { createContext, useContext } from 'react';

type Language = 'en' | 'vi';

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    // Vietnamese to English
    "Vừa xong": "Just now",
    "phút trước": "minutes ago",
    "giờ trước": "hours ago",
    "Hôm qua": "Yesterday",
    "ngày trước": "days ago",
    "Đăng ký mới chờ duyệt": "New registration pending approval",
    "Đã duyệt đăng ký": "Registration approved",
    "Ngựa": "Horse",
    "Chủ": "Owner",
    "Chủ ngựa": "Horse Owner",
    "đăng ký tham gia": "registered to join",
    "Cập nhật giải đấu": "Tournament updated",
    "Lịch đua mới": "New race scheduled",
    "Cuộc đua": "Race",
    "quãng đường": "distance",
    "Mã": "ID",
    "Hành động": "Action",
    "Duyệt": "Approve",
    "Đang tải...": "Loading...",
    "Chi tiết": "Detail",
    "chờ duyệt": "Pending",
    "đăng ký tham gia mới": "New registration",
    "Tạo giải đấu vô địch quốc gia": "National Championship created",
    "Giải đấu Grand Prix Quốc Gia 2026 đã được khởi tạo": "National Grand Prix 2026 Tournament has been created",
    "Đăng ký tham gia mới": "New registration request",
    "Chủ ngựa HorseOwner đã đăng ký ngựa Thunder tham gia giải đấu Grand Prix": "HorseOwner registered Thunder for the Grand Prix Tournament",
    "Phân công trọng tài hoàn tất": "Referee assignment complete",
    "Trọng tài Referee đã được phân công cho cuộc đua Vòng 1": "Referee has been assigned to Round 1 race",
    "Xuất bản kết quả cuộc đua": "Race results published",
    "Admin đã công bố kết quả chính thức cho Giải đua Khang Lẹo": "Admin has published official results for Khang Leo Race",
    "Chào mừng": "Welcome",
    "Chào mừng,": "Welcome,",
    "Tổng quan hệ thống": "System Overview",
    "Mùa giải 2026": "Season 2026",
    "Hệ thống đang hoạt động": "System is active",
    "Xem đăng ký": "View registrations",
    "Quản lý cuộc đua": "Manage races",
    "Người dùng": "Users",
    "Giải đấu": "Tournaments",
    "Lợi nhuận (VNĐ)": "Profit (VND)",
    "Cuộc đua (số nhiều)": "Races",
    "Đăng ký chờ duyệt": "Pending registrations",
    "Cần xử lý trong 24h": "Needs processing within 24h",
    "Hoạt động gần đây": "Recent activity",
    "Chưa có dữ liệu": "No data available",
    "Tạo giải đấu mới": "Create new tournament",
    "Phân công trọng tài": "Assign referees",
    "Lập lịch đua": "Schedule races",
    "Công bố kết quả": "Publish results",
    "Thành tích": "Achievements",
    "Đăng xuất": "Logout",
    "Cài đặt": "Settings",
    "Giao diện": "Theme",
    "Giao diện (Theme)": "Theme",
    "Tối": "Dark",
    "Sáng": "Light",
    "Đóng": "Close",
    "Đăng ký": "Register",
    "Đăng nhập": "Login",
    "Menu": "Menu",
    "Xem tất cả": "View all",
    "Cài đặt hệ thống": "System Settings",
    "Thêm tournament mới vào hệ thống": "Add new tournament to system",
    "Gán referee cho các cuộc đua": "Assign referees to races",
    "Tạo và sắp xếp các cuộc đua": "Create and schedule races",
    "Publish kết quả đã xác nhận": "Publish confirmed results",
    "Tìm kiếm ngựa, cuộc đua, giải đấu...": "Search horses, races, tournaments...",
    "Season 2026": "Season 2026",
    
    // Tournament Management & Labels
    "Thời gian bắt đầu không thể ở quá khứ.": "Start date cannot be in the past.",
    "Thời gian kết thúc phải sau thời gian bắt đầu.": "End date must be after start date.",
    "Thời gian kết thúc đăng ký phải sau thời gian bắt đầu đăng ký.": "Registration end date must be after registration start date.",
    "Thời gian bắt đầu đăng ký không thể ở quá khứ.": "Registration start date cannot be in the past.",
    "Thời gian bắt đầu giải đấu phải sau hoặc bằng thời hạn kết thúc đăng ký.": "Tournament start date must be on or after registration end date.",
    "Thời gian kết thúc giải đấu phải sau thời gian bắt đầu giải đấu.": "Tournament end date must be after tournament start date.",
    "Vui lòng điền đầy đủ tất cả các trường thông tin bắt buộc.": "Please fill in all required fields.",
    "Thành công": "Success",
    "Giải đấu đang ở trạng thái Sắp diễn ra (Upcoming).": "Tournament is now in Upcoming status.",
    "Đã đóng thời hạn đăng ký giải đấu thành công!": "Registration deadline closed successfully!",
    "Đã tự động sắp xếp cuộc đua cho giải đấu.": "Races auto-assigned for tournament.",
    "Đã tự động sắp xếp bảng Chung kết (Top 12) thành công.": "Final bracket (Top 12) auto-assigned successfully.",
    "Đang đóng…": "Closing...",
    "Đóng đăng ký": "Close Registration",
    "Đang sắp xếp…": "Assigning...",
    "Auto xếp làn Pre": "Auto Assign Pre-lanes",
    "Auto xếp Final": "Auto Assign Final",
    "VD: Giải Đua Mùa Thu 2026": "E.g.: Autumn Race 2026",
    "Nhập mô tả chi tiết về giải đấu...": "Enter detailed tournament description...",
    "Mở đăng ký:": "Reg. opens:",
    "Đóng đăng ký:": "Reg. closes:",
    "Xem chi tiết": "View details",
    "Quản lý giải đấu": "Tournament Management",
    "Tạo và quản lý các giải đấu": "Create and manage tournaments",
    "Tạo giải đấu": "Create Tournament",
    "Tất cả": "All",
    "Đang diễn ra": "Active",
    "Sắp diễn ra": "Upcoming",
    "Đã kết thúc": "Completed",
    "Đã hủy": "Cancelled",
    "Tìm giải đấu...": "Search tournaments...",
    "Đang tải danh sách giải đấu...": "Loading tournaments list...",
    "Ngày bắt đầu:": "Start Date:",
    "Ngày kết thúc:": "End Date:",
    "Số vòng đấu:": "Number of Rounds:",
    "Tên giải đấu *": "Tournament Name *",
    "Ngày bắt đầu *": "Start Date *",
    "Ngày kết thúc *": "End Date *",
    "Số vòng đua *": "Number of Rounds *",
    "Hủy": "Cancel",
    "Đang tạo…": "Creating...",
    "Vui lòng điền đầy đủ tất cả các trường.": "Please fill in all fields.",
    "Tạo giải đấu thành công!": "Tournament created successfully!",
    "Các giải đấu đang và sắp diễn ra": "Active and upcoming tournaments",
    "Tất cả các giải đấu đang diễn ra": "All active tournaments",
    "Quay lại danh sách giải đấu": "Back to tournaments list",
    "Đang tải thông tin...": "Loading info...",
    "Không thể tải thông tin giải đấu.": "Failed to load tournament info.",
    "Không tìm thấy giải đấu.": "Tournament not found.",
    "Bắt đầu:": "Start:",
    "Kết thúc:": "End:",
    "Danh sách Cuộc Đua": "Races List",
    "Chưa có cuộc đua nào trong giải đấu này.": "No races in this tournament yet.",
    "Bắt đầu lúc:": "Starts at:",
    "Đường đua:": "Track distance:",
    "Làn tối đa:": "Max lanes:",
    "Xem Chi Tiết": "View Details",
    "Cược Ngay": "Bet Now",
    "Vòng": "Round",

    // Role Labels
    "Administrator": "Administrator",
    "Horse Owner": "Horse Owner",
    "Jockey": "Jockey",
    "Referee": "Referee",
    "Spectator": "Spectator",
    // Landing page — StatsSection & HeroSection (Vietnamese keys → English)
    "ngựa đua trên bảng xếp hạng": "horses on the leaderboard",
    "giải đấu": "tournaments",
    "Trường đua Equestria": "Equestria Racecourse",
    "Lịch thi đấu cập nhật liên tục": "Race schedule updated continuously",
    "trận": "races",
    "Xem kết quả trực tiếp": "View live results",
    "Ngựa trên bảng xếp hạng": "Horses on leaderboard",
    "đang diễn ra": "live now",
    "Cuộc đua trong lịch": "Races in schedule",
    "Nài ngựa chuyên nghiệp": "Professional jockeys",
    "Số liệu trực tiếp từ hệ thống Equestria": "Live data from Equestria system",
    // Landing page — FeaturedTournamentSection (Vietnamese keys → English)
    "Ngày còn để đăng ký": "Days left to register",
    "Vòng đấu": "Rounds",
    "vòng đấu": "rounds",
    "Tham gia ngay": "Join now",
    "Xem giải đấu": "View tournament",
    "Cửa sổ đăng ký": "Registration window",
    "Đã đóng đơn": "Registration closed",
    "Thời gian đăng ký đã trôi qua": "Registration time elapsed",
    // RoleExperienceSection Preview — OwnerPreview
    "Giải thưởng": "Prizes",
    "Hạng mùa": "Season Rank",
    "Ngựa của tôi": "My Horses",
    "Thi đấu": "Competing",
    "Nghỉ ngơi": "Resting",
    "Đăng ký ngựa mới": "Register New Horse",
    // RoleExperienceSection Preview — JockeyPreview
    "lời mời chờ phản hồi": "pending invitations",
    "Số thắng": "Wins",
    "Tỉ lệ thắng": "Win Rate",
    "Lời mời thi đấu": "Race Invitations",
    "Nhận": "Accept",
    "Từ chối": "Decline",
    "Lịch thi đấu hôm nay": "Today's Schedule",
    // RoleExperienceSection Preview — RefereePreview
    "cuộc đua hôm nay": "races today",
    "Kiểm tra ngựa": "Horse Inspection",
    "Vi phạm": "Violations",
    "Vi phạm chờ xử lý": "Pending Violations",
    "Chờ": "Pending",
    "Thời gian khiếu nại": "Appeal Time",
    "Xác nhận vi phạm": "Confirm Violation",
    "Bác bỏ": "Dismiss",
    "hoàn thành": "completed",
    // RoleExperienceSection Preview — SpectatorPreview
    "cuộc đua đang diễn ra": "race in progress",
    "Dự đoán của tôi": "My Predictions",
    "Xem trực tiếp": "Watch Live",
    "Thêm dự đoán": "Add Prediction",
    // AdminDashboardPage stat card trends
    "Hoạt động": "Active",
    "Doanh thu cược": "Betting Revenue",
    "tổng cộng": "total",
    // Sidebar Settings panel
    "Ngôn ngữ (Language)": "Language",
    "Tiếng Việt": "Vietnamese",
    // Topbar
    "Thông báo": "Notifications",
    "Đánh dấu tất cả đã đọc": "Mark all as read",
    "Đánh dấu đã đọc": "Mark as read",
    "Không có thông báo nào": "No notifications",
    "Xem tất cả thông báo": "View all notifications",
    // Vet Dashboard
    "Bảng điều khiển Thú y": "Veterinary Dashboard",
    "Hệ thống quản lý kiểm tra y tế và an toàn sinh học dành cho ngựa đua": "Medical check management and biosafety system for racehorses",
    "Đang tải số liệu thống kê...": "Loading statistics...",
    "Chờ kiểm tra": "Awaiting Inspection",
    "Đã thực hiện": "Performed",
    "Đạt chuẩn y tế": "Medical Standard Met",
    "Nghi nhiễm Doping": "Suspected Doping",
    "Bắt đầu quy trình kiểm tra sức khỏe ngựa": "Start Horse Health Inspection",
    "Xem danh sách các ngựa đã được phê duyệt đăng ký nhưng chưa tiến hành khám lâm sàng.": "View the list of horses approved for registration but not yet clinically examined.",
    "Bắt đầu khám": "Start Inspection",
    // Referee Dashboard
    "Không thể tải thông tin dashboard trọng tài": "Failed to load referee dashboard",
    "Tổng cuộc đua giám sát": "Total Supervised Races",
    "Báo cáo chờ lập": "Reports Pending",
    "Vi phạm ghi nhận": "Violations Recorded",
    "Báo cáo đã gửi": "Reports Submitted",
    "Trọng tài": "Referee",
    "Chờ thực hiện": "To Be Done",
    "Cần xem xét": "Needs Review",
    "Đã hoàn thành": "Completed",
    "Nhiệm vụ giám sát": "Monitoring Duty",
    "Xử lý vi phạm": "Handle Violations",
    "Lịch thi đấu cuộc đua": "Race Schedule",
    "Mã đua": "Race ID",
    "Tên cuộc đua": "Race Name",
    "Thời gian": "Time",
    "Trạng thái": "Status",
    "Thao tác": "Actions",
    "Chưa được phân công cuộc đua nào": "No races assigned yet",
    "Đang chạy": "In Progress",
    "Lịch trình": "Scheduled",
    "Chưa có hoạt động": "No recent activity",
    "Phân công giám sát cuộc đua:": "Race supervision assigned:",
    // Jockey Dashboard
    "Quản lý lời mời hợp đồng và lịch thi đấu của bạn": "Manage your race invitations and racing schedule",
    "lời mời đang chờ": "pending invitations",
    "Xem lời mời": "View Invitations",
    "Lịch thi đấu": "Race Schedule",
    "Lời mời mới": "New Invitations",
    "Chờ phản hồi": "Awaiting Response",
    "Cuộc đua sắp tới": "Upcoming Races",
    "7 ngày tới": "Next 7 days",
    "Số lần thắng": "Total Wins",
    "Mùa 2026": "Season 2026",
    "Ngựa tham gia": "Assigned Horses",
    "Xem ngay": "View Now",
    "Cuộc đua của tôi": "My Races",
    "Lời mời đang chờ": "Pending Invitations",
    "Không có lời mời nào đang chờ": "No pending invitations",
    "Chủ:": "Owner:",
    "Thành tích gần đây": "Recent Achievements",
    "Chấp nhận hợp đồng thành công": "Contract accepted successfully",
    "Từ chối hợp đồng thành công": "Contract declined successfully",
    "Thất bại": "Failed",
    "Hợp đồng": "Contract",
    "đã được xử lý.": "has been processed.",
    "Hạng 1": "1st Place",
    "Hạng 2": "2nd Place",
    "Hạng 3": "3rd Place",
    "Khác": "Other",
    "Tổng đua": "Total Races",
    // Owner Dashboard
    "Tổng quan chuồng ngựa của bạn": "Your stable overview",
    "Mùa giải đang diễn ra": "Season in progress",
    "Quản lý ngựa": "Manage Horses",
    "Đăng ký thi đấu": "Race Registration",
    "Đang thi đấu": "Competing",
    "Sắp thi đấu": "Upcoming",
    "Tiền thưởng": "Prize Money",
    "3 ngày nữa": "3 days left",
    "Chưa có ngựa nào trong chuồng": "No horses in your stable yet",
    "tuổi": "years old",
    "Giới tính": "Gender",
    "Đực": "Male",
    "Cái": "Female",
    "Khỏe mạnh": "Healthy",
    "Lịch thi đấu sắp tới": "Upcoming Schedule",
    "Xem lịch": "View Schedule",
    // Spectator Dashboard
    "Khán giả": "Spectator",
    "Theo dõi giải đấu, đặt cược và quản lý ví của bạn": "Follow tournaments, place bets and manage your wallet",
    "Số dư": "Balance",
    "Live ngay": "Live Now",
    "Đang theo dõi": "Following",
    "chờ kết quả": "pending results",
    "Chưa đọc": "Unread",
    "Dự đoán": "Predictions",
    "Giải đấu sắp tới": "Upcoming Tournaments",
    "Chưa có giải đấu nào": "No tournaments yet",
    "Sắp tới": "Upcoming",
    "Dự đoán gần đây": "Recent Predictions",
    "Chưa có dự đoán nào": "No predictions yet",
    "Đúng": "Correct",
    "Sai": "Incorrect",
    "Đang mở đăng ký": "Registration Open",
    "Đã đóng đăng ký": "Registration Closed",
    "Kiểm tra y tế": "Medical Checking",
    "Sẵn sàng xếp lịch": "Ready To Arrange",
    "Vòng loại": "Pre Round",
    "Vòng chung kết": "Final Round",
    "Trao giải": "Prize Distribution",
    "Giải đấu đang ở trạng thái Đang mở đăng ký (Registration Open).": "Tournament is now in Registration Open status.",
  },
  vi: {
    // English to Vietnamese
    "Cuộc đua (số nhiều)": "Cuộc đua",
    "Dashboard": "Bảng điều khiển",
    "Accounts": "Tài khoản",
    "Tournaments": "Giải đấu",
    "Race Schedule": "Lịch đua",
    "Registrations": "Đăng ký",
    "Assign Referees": "Phân công trọng tài",
    "Referee Management": "Quản lý trọng tài",
    "Publish Results": "Công bố kết quả",
    "Violations": "Vi phạm",
    "Predictions": "Dự đoán",
    "My Horses": "Ngựa của tôi",
    "Race Entry": "Đăng ký đua",
    "Jockey": "Kỵ sĩ",
    "Results & Prizes": "Kết quả & Giải thưởng",
    "Invitations": "Lời mời",
    "My Races": "Cuộc đua của tôi",
    "Schedule": "Lịch trình",
    "Achievements": "Thành tích",
    "My Violations": "Vi phạm của tôi",
    "Demo Flow": "Luồng Demo",
    "Medical Check": "Kiểm tra y tế",
    "Veterinarian": "Bác sĩ thú y",
    "Horse Inspection": "Kiểm tra ngựa",
    "Record Violations": "Ghi nhận vi phạm",
    "Confirm Results": "Xác nhận kết quả",
    "Reports": "Báo cáo",
    "My Wallet": "Ví của tôi",
    "Tournaments & Schedule": "Giải đấu & Lịch trình",
    "Live Results": "Kết quả trực tiếp",
    "My Predictions": "Dự đoán của tôi",
    "Notifications": "Thông báo",
    "Settings": "Cài đặt",
    "Theme": "Giao diện",
    "Dark": "Tối",
    "Light": "Sáng",
    "Close": "Đóng",
    "Logout": "Đăng xuất",
    "Sign In": "Đăng nhập",
    "Register": "Đăng ký",
    "Search horses, races, tournaments...": "Tìm kiếm ngựa, cuộc đua, giải đấu...",
    "Season 2026": "Mùa giải 2026",
    "English": "Tiếng Anh",
    "Menu": "Menu",
    "Welcome": "Chào mừng",
    
    // Role Labels
    "Administrator": "Quản trị viên",
    "Horse Owner": "Chủ ngựa",
    "Referee": "Trọng tài",
    "Spectator": "Khán giả",
    // Landing page — Navbar (English keys → Vietnamese)
    "Leaderboard": "Bảng xếp hạng",
    "Features": "Tính năng",
    "About": "Về chúng tôi",
    // Landing page — HeroSection (English keys → Vietnamese)
    "Premium Racing Platform": "Nền tảng đua ngựa cao cấp",
    "Where Legends": "Nơi những huyền thoại",
    "Race.": "Phi nước đại.",
    "Experience the pinnacle of equestrian sports management. A comprehensive platform for tournament organizers, horse owners, jockeys, referees, and spectators.": "Trải nghiệm đỉnh cao của quản lý thể thao đua ngựa. Nền tảng toàn diện dành cho ban tổ chức giải, chủ ngựa, kỵ sĩ, trọng tài và khán giả.",
    "Explore Platform": "Khám phá nền tảng",
    "Live": "Trực tiếp",
    "Updated live": "Cập nhật trực tiếp",
    // Landing page — Footer (English keys → Vietnamese)
    "The ultimate management platform for elite equestrian tournaments.": "Nền tảng quản lý hàng đầu dành cho các giải đua ngựa đỉnh cao.",
    "Platform": "Nền tảng",
    "Leaderboards": "Bảng xếp hạng",
    "AI Analytics": "Phân tích AI",
    "Live Tracking": "Theo dõi trực tiếp",
    "Company": "Công ty",
    "About Us": "Về chúng tôi",
    "Careers": "Tuyển dụng",
    "Partners": "Đối tác",
    "Contact": "Liên hệ",
    "Legal": "Pháp lý",
    "Privacy Policy": "Chính sách bảo mật",
    "Terms of Service": "Điều khoản sử dụng",
    "Cookie Policy": "Chính sách Cookie",
    "All rights reserved.": "Bản quyền thuộc Equestria.",
    "Made with": "Tạo ra với",
    "for Champions": "dành cho nhà vô địch",
    // Landing page — FeaturesSection (English keys → Vietnamese)
    "Engineered for": "Được thiết kế cho sự",
    "Excellence": "Xuất sắc",
    "A comprehensive suite built specifically for every participant in the horse racing ecosystem.": "Bộ công cụ toàn diện được xây dựng riêng cho mọi thành viên trong hệ sinh thái đua ngựa.",
    "Live Tournament Tracking": "Theo dõi giải đấu trực tiếp",
    "Real-time updates across all active championships. Monitor horse positions, race schedules, and live rankings for every round seamlessly.": "Cập nhật thời gian thực cho mọi giải đấu đang diễn ra. Theo dõi vị trí ngựa, lịch đua và bảng xếp hạng trong từng vòng một cách liền mạch.",
    "Race Prediction System": "Hệ thống dự đoán cuộc đua",
    "Spectators can predict race outcomes, track prediction results, and receive reward notifications for accurate forecasts.": "Khán giả có thể dự đoán kết quả cuộc đua, theo dõi kết quả dự đoán và nhận thông báo phần thưởng cho dự đoán chính xác.",
    "Role-based Dashboards": "Bảng điều khiển theo vai trò",
    "Tailored management experiences for Horse Owners, Jockeys, Referees, Spectators, and Admins.": "Trải nghiệm quản lý được tùy chỉnh cho Chủ ngựa, Kỵ sĩ, Trọng tài, Khán giả và Quản trị viên.",
    "Horse & Tournament Registration": "Đăng ký Ngựa & Giải đấu",
    "Horse owners register horses, assign jockeys, and manage participation. Admins approve entries, schedule races, and oversee the full tournament lifecycle.": "Chủ ngựa đăng ký ngựa, phân công kỵ sĩ và quản lý sự tham gia. Quản trị viên phê duyệt, lập lịch đua và giám sát toàn bộ vòng đời giải đấu.",
    "Referee Oversight System": "Hệ thống giám sát trọng tài",
    "Referees verify horse eligibility before each race, record violations, confirm official results, and file detailed race reports. Results are only published after referee approval.": "Trọng tài xác minh điều kiện ngựa trước mỗi cuộc đua, ghi nhận vi phạm, xác nhận kết quả chính thức và nộp báo cáo chi tiết. Kết quả chỉ được công bố sau khi trọng tài phê duyệt.",
    "Official Verification": "Xác minh chính thức",
    // Landing page — HowItWorksSection (English keys → Vietnamese)
    "Path to": "Con đường đến",
    "Victory": "Chiến thắng",
    "A streamlined, cinematic journey from registration to the winner's circle.": "Hành trình tinh giản, hoành tráng từ đăng ký đến vòng nguyệt quế.",
    "Onboard": "Bắt đầu",
    "Create your profile as an owner, jockey, or spectator with bank-grade security.": "Tạo hồ sơ với tư cách chủ ngựa, kỵ sĩ hoặc khán giả với bảo mật cấp ngân hàng.",
    "Enter horses into premium tournaments and pay entry fees seamlessly.": "Đăng ký ngựa tham gia giải đấu cao cấp và thanh toán phí đăng ký một cách liền mạch.",
    "Race": "Đua ngựa",
    "View real-time schedules, track conditions, and race assignments.": "Xem lịch đua thời gian thực, điều kiện đường đua và phân công cuộc đua.",
    "Triumph": "Chiến thắng",
    "Official times verified by referees and recorded instantly on global leaderboards.": "Thời gian chính thức được trọng tài xác nhận và ghi nhận ngay lập tức trên bảng xếp hạng toàn cầu.",
    // Landing page — CTASection (English keys → Vietnamese)
    "Join The Vanguard": "Tham gia hàng ngũ tiên phong",
    "Enter The Future": "Bước vào tương lai",
    "Of Racing.": "Của đua ngựa.",
    "Don't just participate in the sport. Dominate it with the world's most advanced equestrian platform.": "Đừng chỉ tham gia vào môn thể thao. Hãy thống trị nó với nền tảng đua ngựa tiên tiến nhất thế giới.",
    "Create Your Account": "Tạo tài khoản của bạn",
    // Landing page — RoleExperienceSection (English keys → Vietnamese)
    "Bespoke": "Trải nghiệm được tùy chỉnh",
    "Experiences": "riêng",
    "Interfaces crafted precisely for every participant in the racing ecosystem.": "Giao diện được thiết kế chính xác cho mọi thành viên trong hệ sinh thái đua ngựa.",
    "Manage your stables, register for premium tournaments, and track performance metrics across seasons.": "Quản lý chuồng ngựa, đăng ký giải đấu cao cấp và theo dõi chỉ số hiệu suất qua các mùa giải.",
    "View your upcoming race assignments, study track conditions, and analyze your win probabilities.": "Xem các cuộc đua sắp tới, nghiên cứu điều kiện đường đua và phân tích xác suất chiến thắng.",
    "Input official times, manage disputes, and finalize race results with secure verification.": "Nhập thời gian chính thức, xử lý tranh chấp và hoàn thiện kết quả cuộc đua với xác minh bảo mật.",
    "View tournament schedules, follow live race results and rankings, submit predictions, and receive reward notifications for correct forecasts.": "Xem lịch giải đấu, theo dõi kết quả và bảng xếp hạng trực tiếp, gửi dự đoán và nhận thông báo phần thưởng cho dự đoán chính xác.",
    "Registration Open": "Đang mở đăng ký",
    "Registration Closed": "Đã đóng đăng ký",
    "Medical Checking": "Kiểm tra y tế",
    "Ready To Arrange": "Sẵn sàng xếp lịch",
    "Pre Round": "Vòng loại",
    "Final Round": "Vòng chung kết",
    "Prize Distribution": "Trao giải",
    "Completed": "Đã hoàn thành",
    "Cancelled": "Đã hủy",
    "Tournament is now in Registration Open status.": "Giải đấu đang ở trạng thái Đang mở đăng ký (Registration Open).",
  }
};

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const language: Language = 'en';

  const setLanguage = (_lang: Language) => {
    // Language is locked to English, changing is disabled
  };

  const t = (key: string): string => {
    if (!key) return '';
    
    // Check if translation exists in current language config
    const translations = TRANSLATIONS['en'];
    if (translations && translations[key]) {
      return translations[key];
    }
    
    // Fallback: If current language is the same as key's implied language, return key itself.
    return key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
